import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Die Sidebar wird automatisch aus der Ordnerstruktur unter `docs/` erzeugt.
 * Reihenfolge und Kategorien steuern wir über Standard-Docusaurus-Mittel:
 * - `sidebar_position` im Frontmatter der einzelnen Seiten
 * - `_category_.json` pro Ordner (Label, Position, Verlinkung der Übersichtsseite)
 */
const sidebars: SidebarsConfig = {
  handbuchSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
